### PR TITLE
Templates

### LINKED ISSUE #6: Add bootstrap and jinja templates

### PR DESCRIPTION
**Pull request by yangevelyn**
**Log In:**
 - UI

**Sign Up:**
 - UI
 - Refactored Jinja
 - Connected to Firebase (User nickname and group are saved in realtime database)

**Landing Page:**
 - Added landing.html page

### CODE REVIEW

**Comment by shaynemei** [comment]
removed old commits already merged to master.

**Review by labib666 — APPROVED** [review]
I'd like to know a bit more about the authentication!
But otherwise LGTM!

**Review by shaynemei — APPROVED** [review]
Do we want to add a home button to return to landing page? But I reckon we can do that in another PR.
LGTM!

**Comment by yangevelyn** [comment]
> Do we want to add a home button to return to landing page? But I reckon we can do that in another PR.
> LGTM!

Sure, I'll add it in the branch I'm currently working on.

**Pull request merged**
